blank_issues_enabled: true
contact_links:
  - name: Have questions or need support (for Splunkers)?
    url: https://splunk.slack.com/archives/C03T8QCHBTJ
    about: Please ask questions in the Splunk Slack
  - name: Have questions or need support (for external community)?
    url: https://splunk-usergroups.slack.com/archives/C03SG3ZL4S1
    about: Please ask questions in the Splunk User Groups Slack
